# permissions for end users to edit dependencies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: opa-scaler
    app.kubernetes.io/managed-by: kustomize
  name: dependency-editor-role
rules:
- apiGroups:
  - opas.polimi.it
  resources:
  - dependencies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opas.polimi.it
  resources:
  - dependencies/status
  verbs:
  - get
