# permissions for end users to view opaengines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: opa-scaler
    app.kubernetes.io/managed-by: kustomize
  name: opaengine-viewer-role
rules:
- apiGroups:
  - opas.polimi.it
  resources:
  - opaengines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - opas.polimi.it
  resources:
  - opaengines/status
  verbs:
  - get
