---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opas.polimi.it
  resources:
  - dependencies
  - opaengine
  - opaengines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opas.polimi.it
  resources:
  - dependencies/finalizers
  - opaengines/finalizers
  verbs:
  - update
- apiGroups:
  - opas.polimi.it
  resources:
  - dependencies/status
  - opaengines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - opas.polimi.it
  resources:
  - policies
  verbs:
  - get
  - list
  - watch
