apiVersion: opas.polimi.it/v1alpha1
kind: OpaEngine
metadata:
  labels:
    app.kubernetes.io/name: opa-scaler
    app.kubernetes.io/managed-by: kustomize
  name: opaengine-sample
spec:
  replicas: 1
  image: openpolicyagent/opa:latest-envoy
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  instanceName: opaengine-sample
  policies: []
